apiVersion: lifecycle.keptn.sh/v1alpha3
kind: KeptnTaskDefinition
metadata:
  name: pre-deploy-task
  namespace: keptndemo
spec:
  container:
    name: check
    image: ubuntu
    command:
      - /bin/sh
      - -c
      - echo "Precheck"